
version: 2.1  
jobs:
  smoke-test:
    docker:
      - image: alpine:latest
    steps:
      - run: apk add --update curl
      - run:
          name: "get request for urbanpiper"
          command: |
            URL="https://blog.udacity.com/"
            # Test if website exists
            if curl -s --head ${URL} 
            then
              return 0
            else
              return 1
            fi

workflows:  
  verification:
    jobs:
      - smoke-test
